baseurl: ""

title      : Welcome to The Bond Studio - Bond Origination & Home Loans Experts.
email      : bond.squad@evogroup.co.za
description: Discover your dream home with The Bond Studio! Our expert bond originators unlock the best home loan deals tailored to you, making your property journey seamless and exciting. Start building your future today!
author     : E.Roux / P.Oosthuizen

analytics:
  google: G-XXX

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/img/logo/bond-squad-logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: The Bond Studio 

company: The Bond Studio

url: https://evohomeloans.co.za

address: Werkhuis, First Floor, Kildare Centre, 63 Main Street, Newlands, Cape Town, 7700

broadsheetApiUrl: http://localhost:5113